# Generated by Django 3.2.19 on 2023-07-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Cars', models.IntegerField(verbose_name=200)),
                ('Scooters', models.IntegerField(verbose_name=200)),
                ('Tempo_Auto', models.IntegerField(verbose_name=200)),
                ('Cycles', models.IntegerField(verbose_name=200)),
                ('Buses', models.IntegerField(verbose_name=200)),
                ('Tractor_Trolley', models.IntegerField(verbose_name=200)),
                ('Others', models.CharField(max_length=200)),
            ],
        ),
    ]
