# Generated by Django 3.2.19 on 2023-07-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='Buses',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='Cars',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='Cycles',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='Scooters',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='Tempo_Auto',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='Tractor_Trolley',
            field=models.IntegerField(),
        ),
    ]
