# Generated by Django 3.2.19 on 2023-07-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230701_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='Buses',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='Cars',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='Cycles',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='Others',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='Scooters',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='Tempo_Auto',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='Tractor_Trolley',
            field=models.IntegerField(null=True),
        ),
    ]
