# Generated by Django 3.2.19 on 2023-07-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20230701_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='Day',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
